# Generated by Django 5.1.1 on 2024-09-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblerpc',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название сборки'),
        ),
        migrations.AlterField(
            model_name='assemblerpc',
            name='price_all',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за сборку'),
        ),
        migrations.AlterField(
            model_name='assemblerpc',
            name='user_score',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='case',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название корпуса'),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='case',
            name='proportions',
            field=models.CharField(max_length=100, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='destination',
            field=models.CharField(max_length=100, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название системы охлаждения'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cores',
            field=models.IntegerField(verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название процессора'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='power',
            field=models.CharField(max_length=100, verbose_name='Энергопотребление'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(max_length=100, verbose_name='Тип сокета'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название видиокарты'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='power',
            field=models.CharField(max_length=100, verbose_name='Энергопотребление'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='volume',
            field=models.CharField(max_length=100, verbose_name='Объем памяти'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='chipset',
            field=models.CharField(max_length=100, verbose_name='Тип чипсета'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название материнской платы'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=100, verbose_name='Тип сокета'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Блока питания'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='power',
            field=models.CharField(max_length=100, verbose_name='Энергопотребление'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='volume',
            field=models.CharField(max_length=100, verbose_name='Объем памяти'),
        ),
        migrations.AlterField(
            model_name='storagedrive',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='storagedrive',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название накопителя'),
        ),
        migrations.AlterField(
            model_name='storagedrive',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='storagedrive',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип накопителя'),
        ),
        migrations.AlterField(
            model_name='storagedrive',
            name='volume',
            field=models.CharField(max_length=100, verbose_name='Объем памяти'),
        ),
        migrations.AlterField(
            model_name='typepc',
            name='type',
            field=models.CharField(help_text='Тип ПК (игровой, офисный)', max_length=100, verbose_name='Тип ПК'),
        ),
    ]
