# Generated by Django 4.2.15 on 2024-08-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя')),
                ('email', models.EmailField(max_length=20, verbose_name='Почта')),
                ('password', models.TextField(max_length=20, verbose_name='Пароль')),
            ],
        ),
    ]
